trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Validate
    displayName: "Validate"

    jobs:
      - job: Validate
        displayName: "Validate Project"

        steps:

          - checkout: self
            displayName: "Checkout Repository"

          - script: |
              echo "Validating project structure..."

              test -f Dockerfile
              test -f app/app.py
              test -f app/requirements.txt
              test -d helm/devops-project-1
              test -f terraform/main.tf

              echo "Project structure is valid."
            displayName: "Validate Project Structure"


  - stage: Docker
    displayName: "Docker Build"

    dependsOn: Validate

    jobs:
      - job: DockerBuild
        displayName: "Build Docker Image"

        steps:

          - checkout: self
            displayName: "Checkout Repository"

          - script: |
              docker build \
                -t devops-project-1:$(Build.BuildId) \
                .
            displayName: "Build Docker Image"