apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project-1
  template:
    metadata:
      labels:
        app: devops-project-1
    spec:
      containers:
        - name: devops-project-1
          image: devops-project-1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5