apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-project-1.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-project-1.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-project-1.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}

          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "devops-project-1.fullname" . }}
                  key: APP_ENV

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "devops-project-1.fullname" . }}
                  key: APP_SECRET

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5